spring.application.name=demo1
# Configurações Sankhya
sankhya.oauth.url=https://api.sandbox.sankhya.com.br/authenticate
sankhya.client-id=c7aded48-eee0-4187-8ee1-26fa40b0f52b
sankhya.client-secret=0z8eDmAr8iTxZcaRl3DasbQaBiSetV3W
sankhya.x-token=0ec8c781-945f-4702-99d8-c634ae6fcf76